// <auto-generated />
using APIprueba.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIprueba.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    partial class AppDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("APIprueba.Models.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Rojo",
                            Name = "Lighting McQueen"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Cafe",
                            Name = "Mater"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Azul",
                            Name = "Doc Hudson"
                        });
                });

            modelBuilder.Entity("APIprueba.Models.Tabla1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tabla1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Primero"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Segundo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tercero"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
